#!/usr/bin/env bash

python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-0
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-0
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-0
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-0
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-0
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-0

python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-0
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-0
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-0
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-0
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-0
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-0

python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-1
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-1
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-1
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-1
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-1
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-1

python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-1
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-1
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-1
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-1
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-1
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-1

python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-2
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-2
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-2
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-2
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-2
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --postfix st-2

python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-2
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src A --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-2
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-2
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src D --tgt W --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-2
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt A --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-2
python main_sda.py --cfg cfg/office31-s.json --method dsnet --src W --tgt D --bb resnet --nlayers 101 --nc 31 --resize 256 --size 224 --model-path SRC-TUNE/resnet101-all-tune.params --hybridize --end-epoch 10 --flip --random-crop --random-color --log-itv 10 --fn --postfix st-fn-2
